import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F8FAFC' },
  scrollContent: { flexGrow: 1 },
  topSection: {
    height: 280,
    backgroundColor: '#2563EB',
    justifyContent: 'center',
    paddingHorizontal: 30,
    overflow: 'hidden',
  },
  circle1: {
    position: 'absolute',
    top: -50,
    right: -50,
    width: 200,
    height: 200,
    borderRadius: 100,
    backgroundColor: '#3B82F6',
    opacity: 0.5,
  },
  circle2: {
    position: 'absolute',
    bottom: -20,
    left: -30,
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: '#60A5FA',
    opacity: 0.3,
  },
  headerTextContainer: { zIndex: 1 },
  welcomeText: { fontSize: 18, color: '#DBEAFE', fontWeight: '500' },
  brandName: { fontSize: 42, color: '#FFFFFF', fontWeight: '800', letterSpacing: -1 },
  formCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    marginTop: -40,
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    paddingHorizontal: 30,
    paddingTop: 40,
  },
  title: { fontSize: 28, fontWeight: '700', color: '#1E293B', marginBottom: 8 },
  subtitle: { fontSize: 15, color: '#64748B', marginBottom: 32, lineHeight: 22 },
  inputLabelRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 10 },
  label: { fontSize: 14, fontWeight: '600', color: '#475569' },
  errorTextInline: { fontSize: 12, color: '#EF4444', fontWeight: '500' },
  errorTextBelow: { fontSize: 12, color: '#EF4444', fontWeight: '500', marginTop: -22, marginBottom: 20 },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F1F5F9',
    borderRadius: 16,
    height: 64,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    marginBottom: 30,
  },
  inputError: { borderColor: '#FECACA', backgroundColor: '#FFF1F2' },
  countryPicker: { flexDirection: 'row', alignItems: 'center' },
  flag: { fontSize: 20, marginRight: 8 },
  countryCode: { fontSize: 16, fontWeight: '700', color: '#1E293B' },
  divider: { width: 1, height: 24, backgroundColor: '#CBD5E1', marginHorizontal: 12 },
  input: { flex: 1, fontSize: 17, fontWeight: '500', color: '#1E293B', letterSpacing: 1 },
  primaryButton: {
    backgroundColor: '#2563EB',
    height: 60,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#2563EB',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 5,
  },
  buttonDisabled: { backgroundColor: '#94A3B8', shadowOpacity: 0 },
  buttonContent: { flexDirection: 'row', alignItems: 'center' },
  buttonText: { color: '#FFF', fontSize: 16, fontWeight: '700', marginRight: 8 },
  loaderRow: { flexDirection: 'row', alignItems: 'center' },
  spinner: {
    width: 18,
    height: 18,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#FFF',
    borderTopColor: 'transparent',
    marginRight: 10,
  },
  disclaimer: {
    marginTop: 25,
    textAlign: 'center',
    fontSize: 12,
    color: '#94A3B8',
    lineHeight: 18,
  },
  linkText: { color: '#2563EB', fontWeight: '600' },
});
